import { defaultLocale, type Locale } from './config';

import en from './strings/en.json';
import fr from './strings/fr.json';
import de from './strings/de.json';
import es from './strings/es.json';

/**
 * The site's copy, in four languages.
 *
 * ENGLISH IS THE SHAPE. `en.json` is written by hand and is the only file that
 * defines which keys exist. The other three are generated by
 * `scripts/i18n.mjs` and may be incomplete at any moment, which is the normal
 * state of a translated site rather than a defect. A missing key therefore
 * falls back to English here, key by key, instead of leaving a hole in the
 * page: a German visitor meets one English sentence, not an empty heading.
 *
 * `npm run i18n:status` is what turns those silent fallbacks back into a
 * number you can act on.
 */
const strings: Record<Locale, unknown> = { en, fr, de, es };

type Ui = typeof en;

/** Locale over English, key by key, all the way down. Arrays are replaced whole. */
function merge<T>(base: T, override: unknown): T {
  if (override === undefined || override === null) return base;
  if (Array.isArray(base)) {
    if (!Array.isArray(override)) return base;
    /* Element by element: a translated array that lost an item keeps the
       English one in its place rather than shortening the page. */
    return base.map((item, index) => merge(item, override[index])) as T;
  }
  if (typeof base === 'object' && base !== null) {
    if (typeof override !== 'object' || override === null) return base;
    const out: Record<string, unknown> = { ...(base as Record<string, unknown>) };
    for (const key of Object.keys(out)) {
      out[key] = merge(out[key], (override as Record<string, unknown>)[key]);
    }
    return out as T;
  }
  return (typeof override === typeof base ? (override as T) : base);
}

const cache = new Map<Locale, Ui>();

/** Every string on the site, in `locale`, with English wherever it is missing. */
export function ui(locale: Locale): Ui {
  const hit = cache.get(locale);
  if (hit) return hit;
  const resolved = locale === defaultLocale ? en : merge(en, strings[locale]);
  cache.set(locale, resolved);
  return resolved;
}

/** `interpolate('Hello {name}', { name: 'Ada' })` */
export function interpolate(text: string, values: Record<string, string>): string {
  return text.replace(/\{(\w+)\}/g, (match, key) => values[key] ?? match);
}

/**
 * Whether `locale` really has the copy for one section of the site.
 *
 * The per-key fallback above means a page always renders. That is what a
 * reader wants and exactly what a maintainer must not be allowed to forget, so
 * this is the counterpart: a page asks before rendering whether it is showing
 * a translation or standing in for one, and marks itself accordingly.
 *
 * "Really has it" means every leaf string English defines is present and
 * non-empty here. A section half-translated counts as untranslated: the reader
 * meets a mix of two languages either way, and the notice is the difference
 * between that looking broken and looking honest.
 */
export function hasSection(locale: Locale, section: keyof Ui): boolean {
  if (locale === defaultLocale) return true;
  const source = (en as Record<string, unknown>)[section];
  const target = (strings[locale] as Record<string, unknown> | undefined)?.[section];
  return covers(source, target);
}

function covers(source: unknown, target: unknown): boolean {
  if (typeof source === 'string') return typeof target === 'string' && target.trim() !== '';
  if (Array.isArray(source)) {
    return Array.isArray(target) && source.every((item, index) => covers(item, target[index]));
  }
  if (source && typeof source === 'object') {
    if (!target || typeof target !== 'object') return false;
    return Object.entries(source).every(([key, value]) =>
      covers(value, (target as Record<string, unknown>)[key]),
    );
  }
  return true;
}
